apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk014-stock-api
  namespace: skala-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sk014-stock-api
  template:
    metadata:
      labels:
        app: sk014-stock-api
    spec:
      serviceAccountName: default
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - sk014-stock-api
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: sk014-stock-api
          image: amdp-registry.skala-ai.com/skala25a/sk014-stock-api:1.0.0
          imagePullPolicy: Always
          env:
            - name: LOGGING_LEVEL
              value: DEBUG
            - name: USER_NAME
              value: skala
            - name: NAMESPACE
              value: skala-practice
          ports:
            - containerPort: 8080
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      tolerations:
        - key: "control-plane"
          operator: "Equal"
          value: "amdp"
          effect: "NoSchedule"