server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui # Swagger UI 접속 경로 변경
  api-docs:
    path: /swagger/swagger-docs

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 엔드포인트 노출
      base-path: /health  # actuator base 경로를 /health로 설정
  endpoint:
    health:
      probes:
        enabled: true  # liveness/readiness 프로브 활성화
      show-details: always

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    root: INFO
    '[com.sk.skala]': DEBUG

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:h2:mem:skala-stock
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

application:
  name: "SKALA-STOCK-API"
skala:
  user-name: ${USER_NAME:skala}
  namespace: ${NAMESPACE:skala-env}
